#!/usr/bin/env python

import os
import sys
import getopt
import re
import pprint
from ftplib import FTP

import settings
import models

def is_safe(s):
    if re.match("^[\w\.-]+$", s):
        return True
    return False

def get_temp_path(base_name):
    return os.path.join(settings.ENCDIR, base_name)

def get_preset(preset_name):
    try:
        return settings.PRESETS[preset_name]
    except KeyError:
        return "preset not defined"
    
def usage():
    print """usage:
python encload.py -j <job_id>       start job
python encload.py -c                create sqlite table
python encload.py -t                run tests"""

def main(argv):
    try:
        opts, args = getopt.getopt(argv, "hj:ct", ["help", "job_id=", "create_tables", "test"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt in ("-j", "--job_id"):
            models.Job.encload(arg)
            sys.exit()
        elif opt in ("-c", "--create_tables"):
            models.create_tables()
            print "tables created"
            sys.exit()
        elif opt in ("-t", "--test"):
            models.test()
            print "test completed"
            sys.exit()
        else:
            usage()
            sys.exit()

if __name__ == "__main__":
    main(sys.argv[1:])
